name: CI (Build and Test)

on:
  push:
    branches: [ main ] # Triggers on push to the main branch 

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Use a current Node.js LTS version

      - name: Install Dependencies
        run: npm install

      # NOTE: The heavens-above repo doesn't have a lint script.
      # You can add one to package.json, e.g., "lint": "eslint src/**"
      # For this assignment, we'll create a placeholder step.

        run: echo "Skipping linting step as no 'npm run lint' script is defined."
        # To make this a real step, add a lint script to package.json and change this line to:
        # run: npm run lint

      # NOTE: The heavens-above repo doesn't have a test script.
      # You can add one, e.g., using Jest.
      # For this assignment, we'll create a placeholder step.
      - name: Run Tests
        run: echo "Skipping tests as no 'npm test' script is defined."
        # To make this a real step, add a test script to package.json and change this line to:
        # run: npm test