name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., v1.0.0)'
        required: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create release package
        run: |
          npm install
          zip -r release.zip public/ src/ package.json run.js README.md
          
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "release.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.inputs.version }}
          name: "Release ${{ github.event.inputs.version }}"
          generateReleaseNotes: true