name: Scheduled Tasks

on:
  schedule:
    # Runs "at 05:00 UTC every day" 
    - cron: '0 5 * * *'

jobs:
  run-daily-task:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Daily Task
        run: |
          echo "Running a simulated daily task, like a data backup or health check..."
          # In a real app, you might run a script:
          # npm run backup-database
          echo "Daily task complete."